### ISSUE TITLE
Not able to rackup

### ISSUE THREAD

**Issue by judavi** [openblockchains/tulipmania#1]
Hi! I'm not an expert on Ruby but I'm interested in your project so I'm trying to run the project using rackup but I'm getting this error:

![captura de pantalla 2017-12-19 a la s 5 38 27 p m](https://user-images.githubusercontent.com/1766933/34170602-61404d8c-e4e3-11e7-846d-16afdf4630af.png)

I will appreciate any help

**Comment by geraldb** [comment]
Please try the centralbank - this repo (tulipmania) is still work in progess (copied for making changes from centralbank). Please check back in two or three days. Cheers.

**Comment by judavi** [comment]
I will, thanks @geraldb

**Comment by geraldb** [comment]
FYI: A first tulipmania version is now online / published. Cheers. Prosit 2018.
